### ISSUE TITLE
Automate release process

### ISSUE THREAD

**Issue by ignatev** [gennady-lebedev/hard-core#27]
Release process
----
We should create a simple automated flow for testing/publishing releases and snapshots to the central maven repo. 

## Tasks
- [x] Claim dev.rudiments group in maven central
- [x] Use public hosted CI for building, testing snapshots on commit
- [x] Automate maven central release publishing

**Comment by ignatev** [comment]
Group dev.rudiments prepared, now we can push releases into the maven central
https://issues.sonatype.org/browse/OSSRH-50585
